### PR TITLE
Allow download of local Support assist without the need of a GUI

### PR DESCRIPTION
**Pull request by shade34321**
Instead of using the webbrowser to download the support assist, we can now directly hit the endpoint and write the file locally.

Also moved the accept to earlier since before it was erroring out for us. Also allow checking if we already accepted it and only accepting it if we haven't accepted the EULA.

### CODE REVIEW

**Comment by texroemer** [comment]
@shade34321 

Thanks for the suggestions and code changes!

-Tex

**Comment by shade34321** [comment]
Thank you! If you don't mind, can you mark this as `hacktoberfest-accepted` :)

https://hacktoberfest.com/participation/#maintainers

**Comment by texroemer** [comment]
Done. I also had to make a few changes to the script, some error conditions were not handled correctly especially when trying to pass in arguments export and accept at the same time. Also updated the script examples and removed download argument.

**Comment by shade34321** [comment]
Thanks, sorry about that. I would have fixed them had I known.

**Pull request merged**
